### ISSUE TITLE
请问tina是否不支持云开发？

### ISSUE THREAD

**Issue by linchinghao** [tinajs/tina#11]
- project.config.json 可以自定义配置吗？
- src目录下添加新文件不会打包到dist？

**Comment by imyelo** [comment]
1. 可以修改 project.config.js
2. src 内的文件需要经过 webpack 才会输出到 dist。

用 tina 默认的项目模板不能直接支持云开发。在默认模板的基础上可以通过做这些调整支持：

- 将 project.config.json 从存放在 dist 目录改为存放在项目根目录
- 确认 project.config.json 受 git 管理 (即没有被记入 .gitignore)
- 在 project.config.json 中配置云函数代码的目录路径，比如 `"cloudfunctionRoot": "./functions/"`

**Comment by linchinghao** [comment]
@imyelo 感谢!这么晚还回复😂还有个疑问，project.config.json 是 webpack 生成的吗？src下新建 project.config.json 编译后不会覆盖掉dist下的 project.config.json。现在我是用 `CopyWebpackPlugin` 拷贝到 dist 目录下，对 webpack 不是特别熟悉。

**Comment by imyelo** [comment]
不是 webpack 生成的，因为微信开发者工具

**Comment by linchinghao** [comment]
@imyelo thank u!
