### ISSUE TITLE
tina什么时候支持分包和引入iview-weapp等插件的功能啊？

### ISSUE THREAD

**Issue by kaven85** [tinajs/tina#13]
tina什么时候支持分包和引入iview-weapp等插件的功能啊？

**Comment by imyelo** [comment]
现在使用 [mina-webpack](https://github.com/tinajs/mina-webpack) ^1.0.0 的版本就可以直接支持了。

如果是新项目，推荐使用 [template-mina](https://github.com/tinajs/template-mina) 生成新的项目模板。
如果是旧项目，暂时没有特别好的办法升级，需要参考 https://github.com/tinajs/template-mina/compare/v0.1.16...v1.1.1 手动修改 webpack、babel、package.json 的配置。
