### ISSUE TITLE
能支持原生的wxs吗

### ISSUE THREAD

**Issue by lmw6412036** [tinajs/tina#20]

**Comment by imyelo** [comment]
wxs 是支持的，但在 wxs 文件内不支持引用其他文件。

**Comment by imyelo** [comment]
最新版本的 [mina-webpack](https://github.com/tinajs/mina-webpack) 已支持解析 wxs（包括在 wxs 内引用其他文件）。

e.g.: https://github.com/tinajs/mina-webpack/blob/f88a37a/example/src/pages/message.mina#L13
