### ISSUE TITLE
app.js 中由插件引入都方法没有 polyfill

### ISSUE THREAD

**Issue by baranwang** [tinajs/tina#31]
我自定义的插件中有用到 `async/await` 方法，但是看最后编译进 `app.js` 后好像没有 polyfill，导致在 iOS 端无法正常运行。
![image](https://user-images.githubusercontent.com/11427801/54908839-bde71b00-4f23-11e9-9551-8d7424214913.png)

**Comment by baranwang** [comment]
在 `webpack.config.js` 中手动 include 插件文件后编译可以正常 polyfill 了

**Comment by imyelo** [comment]
那我关闭这个问题了 😄
如果还有问题请随意打开
