### ISSUE TITLE
自动引入组件需求

### ISSUE THREAD

**Issue by callmesoul** [tinajs/tina#51]
总所周知，小程序不支持全局的组件跟api，所以自己写的自动定义组件在页面上用时总是要很繁琐的地一个个去引用组件。
最近看了别人的一个vue项目，就是全局组件在一个目录下，会自动注册成全局组件。

于是想tina能不能使用 webpack，在页面tempalte查找使用的自定义组件节点，去自动查找引入自定义组件了，这样就不用一个个引用了 。对于自定义顶部导航等全局的组件来说方便 多了

**Comment by x-bao** [comment]
原生支持全局组件的，见[文档-全局配置-usingComoonents](https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html)

> usingComponents
开发者工具 1.02.1810190 及以上版本支持
> 在此处声明的自定义组件视为全局自定义组件，在小程序内的页面或自定义组件中可以直接使用而无需再声明。

**Comment by callmesoul** [comment]
看到最近更新了
