### ISSUE TITLE
page 怎么 使用 selectComponent

### ISSUE THREAD

**Issue by callmesoul** [tinajs/tina#57]
`this.selectComponent("#image-cropper");`
`this.selectComponent is not a function;`

**Comment by imyelo** [comment]
没有被映射的 [属性和方法](https://github.com/tinajs/tina/blob/cd292da/src/core/layers/page.js#L12-L13) 可以通过 [this.$source](https://tina.js.org/#/api/README?id=pagesource) 访问，即 `this.$source.selectComponent('#image-cropper')`。

欢迎 PR~

**Comment by callmesoul** [comment]
thx
