### ISSUE TITLE
请问能不能支持把config放到script标签内部？

### ISSUE THREAD

**Issue by KarnaughK** [tinajs/tina#58]
类似 wepy 那样。。。
提示这个 issues 的主要原因和 #55 是一样的，webstorm折腾了半天还是没法格式化 <config> 标签内的代码，自己又不会写插件。。。如果能把 config 放到 script 内，作为一种可选的形式，那就真的太感谢了

**Comment by KarnaughK** [comment]
努力了一晚上，自己写了一个简陋的 loader，有需要的朋友可以用一下
#### 先展示一下用法
```
<script>
/*config-start*/
let TinaCompatibleConfig = {
  "window": {
    "navigationBarBackgroundColor": "#25798a",
    "backgroundColor": "#25798a"
  },
  "pages": [
    "pages/home.mina"
  ],
  "tabBar": {
    "custom": true,
    "color": "#000000",
    "selectedColor": "#000000",
    "backgroundColor": "#000000",
    "list": [
      {
        "pagePath": "page/component/index",
        "text": "组件"
      },
      {
        "pagePath": "page/API/index",
        "text": "接口"
      }
    ]
  },
}
/*config-end*/

App({})
</script>

```
`/*config-start*/` 和 `/*config-end*/`是必须要写的

loader 会把 `/*config-start*/` 和 `/*config-end*/` 中间的内容去掉 `let TinaCompatibleConfig =` 后转移到 config 标签中，这样就解决了 webstorm 没法格式化 config 标签里代码的问题

### 由于不会、也没时间弄 npm 包，代码就粘这了，没几行，复制进去就行了
#### 1. 自定义 mina-config-loader.js

文件位置 `项目根目录/loaders/mina-config-loader.js `
```
module.exports = function (source, a, b) {
  // console.log('================== def ==================')
  // console.log(source)
  let configReg = /\/\*config-start\*\/([\d\D]*?)\/\*config-end\*\//g
  let config = source.match(configReg)
  if (config && config[0]) {
    config = config[0]
    source = source.replace(config, '')
    config = config.replace('/*config-start*/', '')
    config = config.replace('let TinaCompatibleConfig =', '')
    config = config.replace('/*config-end*/', '')
    source = '<config>\n' + config + '\n</config>\n\n' + source
    // console.log('================== after ==================')
    // console.log(source)
  }
  return source;
};

```
#### 2. 在 webpack.config.js 里引入

在 resolveLoader 里添加： './loaders/'
```
module.exports = {
  resolveLoader: {
    // 去哪些目录下寻找 Loader，有先后顺序之分
    modules: ['node_modules', './loaders/'],
  },
  ......
}
```
在 modules.rules 里添加 loader，放到两个mina-loader 下边
```
module.exports = {
  .............
  module: {
    rules: [
      {
        test: /\.mina$/,
        exclude: /node_modules/,
        use: [
          {
            loader: '@tinajs/mina-loader',
            options: {
              loaders,
            },
          },
        ],
      },
      {
        test: /\.mina$/,
        include: /node_modules/,
        use: '@tinajs/mina-loader',
      },
      {
        test: /\.mina$/,
        exclude: /node_modules/,
        loader: 'mina-config-loader'
      },
    .............
    ],
  .............
}
```

#### 3. 使用模板
```
<template>

</template>

<script>
/*config-start*/
let TinaCompatibleConfig = {
  "usingComponents": {
    "author": "../components/author.mina"
  }
}
/*config-end*/

Page({
})
</script>

<style>

</style>

```

**注意 `/*config-start*/` `/*config-end*/` 和 `let TinaCompatibleConfig =` 是必须有的**
前两者是用来界定 config 的范围，最后一段是因为。。。不把 config 赋值给一个对象的话一格式化就炸了啊🤣

**Comment by KarnaughK** [comment]
自己尝试写了个loader，发现还是不能用，头疼。。。

**Comment by imyelo** [comment]
抱歉我最近精力不足以支持这类改动，但如果感兴趣的话，非常欢迎你做些尝试。我的思路是这样的：

1. 如果要将 config 放在 script 里，比较好的设计是在 script 中用 `export` 导出，例如：

	```javascript
	export const config = {
	  // ... value of <config>
	}
	```
	
	为了保持一致，`Page.define` 也应改用这种方式设计，即：
	
	```javascript
	import { Page } from '@tinajs/tina'
	
	Page.define({
	  // ...
	})
	```
	
	改为
	```javascript
	export const config = {
	  // ... value of <config>
	}
	
	export default {
	  // ... arguments of Page.define
	)
	```
	
	这样的话，就需要用到 loader 来读取 `<script>` 中 `export` 的值；对 `export default` 而言还需要能够自动导入 `@tinajs/tina`，插入 `Page.define(...)`。
	
	这个操作应该由谁来做呢？交给 mina-loader 是不适合的，因为会因此增加它和 tina 之间的耦合度。但可以利用 mina-loader 中的 `transform` 参数为各个区块添加额外处理。这个参数的设计初衷是为了和  https://github.com/tinajs/translators/ 组合支持转译跨生态小程序的，例如支持支付宝小程序。对于 #58 这个场景，也恰好类似。有兴趣的话可以参考下这个文件：https://github.com/tinajs/translators/blob/593ffa7/packages/%40tinajs/translator-ant/lib/translations/script.js
	
2. 除了 loader 的问题之外，还需要对 mina-entry-webpack-plugin 做改动。

	这个插件会遍历 `<config>` 的内容，生成一份包含所有页面和组件的列表。既然 config 的值移至了 `<script>` 当中，那么插件也就需要对应地转至 `<script>` 中读取。在 mina-entry-webpack-plugin 中，读取的操作已经抽象成了 ConfigReader，例如 https://github.com/tinajs/mina-webpack/blob/de639d0/packages/mina-entry-webpack-plugin/src/index.ts#L142 ，但可惜这个接口还不支持接受外部的值，所以如果需要支持这个需求，还应先对 mina-entry-webpack-plugin 做改动，支持传入自定义的 ConfigReader  (类似 mina-loader 的 `transform`)。

希望有帮助。
