### ISSUE TITLE
在set data 的时候不能trigger wxml 层的 class 中的 变量 更新

### ISSUE THREAD

**Issue by alonbee** [tinajs/tina#6]
嗨  你好！ 感谢开发这个框架  目前为止  非常好用  但是遇到一个问题无法解决

我尝试使用 Ripples.wxss 添加animation  一个常用的方法使用 setData 来控制 animation  比如 通过改变 data 中的 bounceShow 就可以给 以下 这个view 添加 bounce 动画
`<view class="ripple {{bounceShow ? bounce:''}}">bounce</view>
`
但是 用了 tina.js 之后    无法看到 在 wxml 中的 data的更新   在这个例子中  bounceShow 一直不会被改变    能提供一些debug的思路吗？   感谢🙏

**Comment by imyelo** [comment]
Hi @alonbee !

是不是 `'bounce'` 字符串忘了添加引号？ 应该是：

```html
<view class="ripple {{ bounceShow ? 'bounce' : '' }}">bounce</view>
```

如果确认 wxml 没问题的话，可以试试在微信开发者工具里的 AppData 面板中观察 data 有没有更新，排查是不是 setData 的方式有问题。另外可以把完整的 `.mina` 文件发一下。

**Comment by alonbee** [comment]
是忘了加引号。。。   太感谢勒 ！！！
