### ISSUE TITLE
tinajs 支持引入原生代码的 Components 吗？

### ISSUE THREAD

**Issue by tinyRatP** [tinajs/tina#65]
正在使用 tinajs，请问 tinajs 支持引入原生代码的 components 吗？如果支持，该怎么引入呢？

例如，我想引入 [trtc-room components](https://cloud.tencent.com/document/product/647/32183)

**Comment by imyelo** [comment]
支持，和原生项目里的使用方法一样。

例如：https://github.com/tinajs/mina-webpack/blob/master/example/src/pages/home.mina#L7

**Comment by tinyRatP** [comment]
trtc-room 是腾讯官方的 components，是 `wxml wxss js`，而不是单一文件 `mina`。

因此，我只能将其重构为 `mina` 吗？

**Comment by imyelo** [comment]
不需要重构成 `.mina` 文件，tina 直接支持文件分离的组件。

上面报错的原因是因为 `/components/trtc-room/template/grid/grid.wxml` 里引用 `./static/switch.png` 等图片文件时的路径有问题，你试下将这些路径修改成 `'../../static/switch.png'` 或 `'/components/trtc-room/static/switch.png'` 或 `require('../../static/switch.png')` 的形式。

**Comment by tinyRatP** [comment]
thxs.

**Comment by tinyRatP** [comment]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/15377472/77895749-cf3ad400-72a9-11ea-9813-2432cfd5a299.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/15377472/77895771-d5c94b80-72a9-11ea-9040-26196bff5322.png">
<img width="219" alt="image" src="https://user-images.githubusercontent.com/15377472/77895782-d9f56900-72a9-11ea-9be6-ef8424a650cc.png">
<img width="227" alt="image" src="https://user-images.githubusercontent.com/15377472/77895831-f0032980-72a9-11ea-9713-6dc29b4f1d52.png">

在使用腾讯云第三方 TRTC-Room 时，tinajs 编译后缺失文件，该如何解决呢？

**Comment by imyelo** [comment]
看了下，[TRTC-ROOM 最新的代码里又混用了相对路径和依赖包路径的写法](https://github.com/tencentyun/TRTCSDK/blob/3627f66/WXMini/components/trtc-room/trtc-room.js#L1-L7)。微信原生小程序将这类路径解析为相对路径，破坏了 [Node.js Modules Resolving 的约定](https://nodejs.org/api/modules.html#modules_all_together)，给引用依赖包的场景埋下了坑，使人困扰，是欠考虑的设计。

如果你的项目是将 `trtc-room` 复制至项目目录中使用，可以直接修改这些引用的路径，添加前缀 `./`：

```diff
- import UserController from 'controller/user-controller.js'
+ import UserController from './controller/user-controller.js'
```

这种形式含义更清晰，也建议向 trtr-room 的仓库提交 Issue / PR。

另外 tina (mina-webpack) 针对小程序组件 (Component) 的引用声明 [兼容了微信不带 `./` 前缀的相对路径](https://tina.js.org/#/guide/single-file-component?id=%e5%bc%95%e7%94%a8%e7%bb%84%e4%bb%b6%e7%9a%84%e6%89%80%e6%9c%89%e8%b7%af%e5%be%84%e8%a7%84%e5%88%99)，但除此以外遵循的都是 [Node.js Modules Resolving 的规则](https://nodejs.org/api/modules.html#modules_all_together)。

**Comment by tinyRatP** [comment]
谢谢耐心解答。
