### ISSUE TITLE
请问支持分包、插件和npm引入第三方组件吗？

### ISSUE THREAD

**Issue by ldwonday** [tinajs/tina#9]
如题，不知道这个框架有没有支持这些功能？

**Comment by imyelo** [comment]
- 分包目前还不支持。
- 插件可以正常使用；如果希望创建插件项目，可以了解一下 @lizheming 的 [template-mina-plugin](https://github.com/lizheming/template-mina-plugin)。
- 第三方组件目前只支持以 `.mina` 格式发布的包；原小程序的第三方组件暂时还不能被直接引入，但这个 feature 已经在做了，不久后就能够支持。相关的 issues：https://github.com/tinajs/tina/issues/8，https://github.com/tinajs/mina-webpack/pull/25。

**Comment by imyelo** [comment]
https://github.com/tinajs/mina-webpack/pull/39 已支持简单的分包

**Comment by imyelo** [comment]
https://github.com/tinajs/mina-webpack/pull/40 已支持引入原小程序的第三方组件

**Comment by ldwonday** [comment]
@imyelo 希望可以写一个和dva结合的例子！

**Comment by jsGood** [comment]
微信原生的第三方组件要是支持就好了，wepy也是不支持。。。期待。。

**Comment by lizheming** [comment]
@jsGood https://github.com/tinajs/tina/issues/9#issuecomment-421120408 和这个说的支持引入第三方组件不是一个意思？还是我理解错了？

**Comment by jsGood** [comment]
原微信小程序的第三方插件，现在wepy和tina都是支持自己格式的第三方插件，所以引入第三方组件是可以的，有限制，就是必须是tina格式写的。我没理解错吧 @lizheming

**Comment by lizheming** [comment]
@jsGood 不是，https://github.com/tinajs/mina-webpack/pull/40 这个 PR 解决的就是引入 wxml, wxs, wxss 等原生组件格式的问题。

**Comment by imyelo** [comment]
@jsGood 微信原生的第三方组件也是支持的 😄
